### ISSUE TITLE
Node is either not visible or not an HTMLElement

### ISSUE THREAD

**Issue by christiancannata** [jvandenaardweg/linkedin-profile-scraper#13]
I think you can put a try - catch if can not find button, what do you think about it?
/dist/index.js:264

`Scraper (run): An error occurred during a run.
(node:13284) UnhandledPromiseRejectionWarning: Error: Node is either not visible or not an HTMLElement
    at ElementHandle._clickablePoint (/Users/christiancannata/projects/linkedin_spider/node_modules/puppeteer/lib/JSHandle.js:170:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
    at ElementHandle.<anonymous> (/Users/christiancannata/projects/linkedin_spider/node_modules/puppeteer/lib/helper.js:94:19)
    at LinkedInProfileScraper.<anonymous> (/Users/christiancannata/projects/linkedin_spider/node_modules/linkedin-profile-scraper/dist/index.js:264:42)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/christiancannata/projects/linkedin_spider/node_modules/tslib/tslib.js:112:62)
    at process._tickCallback (internal/process/next_tick.js:68:7)
`

**Comment by jvandenaardweg** [comment]
Thanks for opening an issue for this @christiancannata !

Can you create a PR for this?

According to your findings, the problem probably lies here:
https://github.com/jvandenaardweg/linkedin-profile-scraper/blob/master/src/index.ts#L546
and or here:
https://github.com/jvandenaardweg/linkedin-profile-scraper/blob/master/src/index.ts#L561
