### ISSUE TITLE
Error: Failed to launch the browser process!

### ISSUE THREAD

**Issue by nort4n** [jvandenaardweg/linkedin-profile-scraper#44]
I'm getting this error on Ubuntu and MacOS. Tried installing chromium. Can I redirect puppeteer to this installation? Any suggestions? 

```
Scraper (setup): Launching puppeteer in the background...
Scraper (setup): An error occurred during setup.
/home/norman/dev/scrape-playground/scrape-playground/node_modules/linkedin-profile-scraper/node_modules/puppeteer/lib/launcher/BrowserRunner.js:189 
            reject(new Error([
                   ^

Error: Failed to launch the browser process!
/home/norman/dev/scrape-playground/scrape-playground/node_modules/linkedin-profile-scraper/node_modules/puppeteer/.local-chromium/linux-756035/chrome-linux/chrome: error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/home/norman/dev/scrape-playground/scrape-playground/node_modules/linkedin-profile-scraper/node_modules/puppeteer/lib/launcher/BrowserRunner.js:189:20)
    at Interface.<anonymous> (/home/norman/dev/scrape-playground/scrape-playground/node_modules/linkedin-profile-scraper/node_modules/puppeteer/lib/launcher/BrowserRunner.js:179:65)
    at Interface.emit (node:events:525:35)
    at Interface.close (node:readline:590:8)
    at Socket.onend (node:readline:280:10)
    at Socket.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1358:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Comment by TR-EIP** [comment]
Same issue for me... 
When I run Puppeteer by itself, I don't have any problem, but when I run the scraper, I get the same error on launch.
Have you found a solution, @nort4n ?

**Comment by joaovdiasb** [comment]
same here
